---
title: "hypothesis test"
author: "Annabel Shein"
date: "12/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(infer)
library(readr)
library(dplyr)
library(ggplot2)
library(oilabs)
```

$H_0: \mu_{intgross2013-pass} - \mu_{intgross2013-fail} = 0$

$H_A: \mu_{intgross2013-pass} - \mu_{intgross2013-fail} > 0$

```{r}
bechdelSampleNEW  <- read.csv(file = "bechdelSampleNEW.csv", header = TRUE)

```


```{r}
obs_diff_intgross_binary <- bechdelSampleNEW %>% 
  specify(intgross_2013 ~ binary) %>% 
  calculate(stat = "diff in means", order = c("PASS", "FAIL"))

obs_diff_intgross_binary
```


```{r}
set.seed(108)

intgross_in_null_world <- bechdelSampleNEW %>% 
  specify(intgross_2013 ~ binary) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 5000, type = "permute")
```

```{r}
intgross_diff_under_null <- intgross_in_null_world %>% 
  calculate(stat = "diff in means", order = c("PASS", "FAIL")) 

intgross_diff_under_null %>% 
  slice(1:5)
```

```{r}
visualize(intgross_diff_under_null) +
  shade_p_value(obs_stat = obs_diff_intgross_binary, direction = "both") + 
  labs(x = "Difference in mean international gross for movies that pass or fail the Bechdel Test", y = "Count",
       title = "Null distribution",
      subtitle = "Actual difference observed in the data is marked in red")
```

```{r}
intgross_diff_under_null %>% 
  get_pvalue(obs_stat = obs_diff_intgross_binary, direction = "greater") 
```

Box plot

```{r}
ggplot(data = bechdelSampleNEW, aes(x = binary, y = intgross_2013)) +
  geom_boxplot(fill = "plum") + labs(title = "Comparison of International Gross Between \n Movies  That Pass and Movies  That Fail  \n the Bechdel Test", x = "Whether a Movie Passes or Fails the Bechdel Test", y = "International Gross \n (USD, Adjusted for Inflation in 2013  ") + theme(text = element_text(size = 15))
```

summary statistics

```{r}
bechdelSampleNEW %>%
  summarize(n = n(), 
            count_pass = sum(binary == "PASS"),
            count_fail = sum(binary == "FAIL"),
            mean_int = mean(intgross_2013),
            median_int = median(intgross_2013),
            sd_int = sd(intgross_2013) )
```


```{r}
bechdelSampleNEW %>%
  group_by(binary) %>%
  summarize(meanint = mean(intgross_2013, na.rm = TRUE))


```



WHY CANT I GET STATS ON INTGROSS


CI
```{r}
bechdelSampleNEW %>% 
  specify(intgross_2013 ~ binary) %>%
  generate(reps = 5000, type = "bootstrap") %>% 
  calculate(stat = "diff in means", order = c("PASS", "FAIL")) %>% 
  get_ci(level = 0.95)
```

