---
title: "BechelSampleMultipleRegression"
author: "Christian Madrigal"
date: "12/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(moderndive)
```

```{r}
bechdelSampleNEW <- read.csv(file="bechdelSampleNEW.csv", header=TRUE)
```

```{r}
model_intgross2013 <- lm(intgross_2013 ~ binary + budget_2013 + imdb.1+decade_code, data = bechdelSampleNEW)

get_regression_table(model_intgross2013, digits = 5) 
```

```{r}
summary(model_intgross2013)
```


<<<<<<< HEAD
Checking conditions




```{r}
intgross_resid <- get_regression_points(model_intgross2013)
```

residual vs fitted values

```{r}
ggplot(intgross_resid, aes(x = intgross_2013_hat, y = residual))+ 
  geom_point() + 
  geom_abline(slope = 0, intercept = 0, color = "red") + 
  labs(title = "Residual versus Fitted")


plot(model_intgross2013, which=1)
```


residuals vs budget

```{r}
ggplot(intgross_resid, aes(x= budget_2013, y = residual)) + 
  geom_abline(slope = 0, intercept = 0, color = "red")+ 
  geom_point() + 
  labs(x = "budget")
```


residuals vs imdb score

```{r}
ggplot(intgross_resid, aes(x= imdb.1, y = residual)) + 
  geom_abline(slope = 0, intercept = 0, color = "red")+ 
  geom_point() + 
  labs(x = "imdb score")
```

histogram of residuals


```{r}
ggplot(intgross_resid, aes(x= residual)) + 
  geom_histogram(binwidth = 50000000, fill = "coral", color = "white") + 
  labs(x = "residuals")
```

residuals vs binary

```{r}
ggplot(intgross_resid, aes(x= binary, y = residual)) + 
  geom_abline(slope = 0, intercept = 0, color = "red")+ 
  geom_jitter() +
  geom_point() + 
  labs(x = "Binary", title = "Residuals for the binary: whether or not the movie passed the bechdel test")
```



